### ISSUE TITLE
more than 2 levels of references not working as expected.

### ISSUE THREAD

**Issue by rjaen** [specmesh/specmesh-build#427]
**Describe the bug**
Having 3 schemas A, B and C, A references to B,  references to C. When schemas are loaded C is read fine, B is read fine with its C dependency, then A wants to load load B, but references needed by B are not loaded so B fails by not finding C reference.

**To Reproduce**
Adding reduced version of the real files, they have references each other, so provisioning files in order Timer (C), then RequestRowModel (B) and finally RfqEventContext(A) should show the error when loading A.

`org.apache.avro.SchemaParseException: Type not supported: com.test.rfq.single.Timer`

	`at org.apache.avro.Schema.parse(Schema.java:1797)
	at org.apache.avro.Schema.parse(Schema.java:1823)
	at org.apache.avro.Schema.parse(Schema.java:1736)
	at `

**Expected behavior**
Provisioning should work just fine and references should work.

**Actual behaviour**
References are not working for 3 levels. They do for 2 levels B depending on A.

**Version info**
- What version of SpecMesh is affected? 0.9.4 and 0.14.0
- What OS are you on? Mac Os

**Comment by big-andy-coates** [comment]
Hi @rjaen, I'm fairly certain this is fixed in the latest release.

**Comment by rjaen** [comment]
will report back once we confirm it, thanks!

**Comment by big-andy-coates** [comment]
Actually, I think I found your bug while working on something else. Fixing inbound.
